#!/usr/bin/env zsh
# This function takes one argument, the port name, and cd's into its directory.

function port-cd {
    local port_name=$1

    port-exists $port_name || return -1

    cd $(port dir $port_name)
}
