#!/usr/bin/env zsh

local port_name=$1

port-exists $port_name || return -1

port log $port_name | sed -e 's/^ *\(warning:.*\)/^[[38;5;202m\1^[[0m/' -e 's/^ *\(error:.*\)/^[[38;5;196m\1^[[0m/' | $PAGER -R
