#!/usr/bin/env zsh

local port_name=$1
if [[ -z $port_name &&  ! -r ./Portfile ]]; then
    echo "Error: Not in port directory and no port specified" 1>&2
    return -1
fi
port info $port_name > /dev/null
return $?
